<script setup>
import AppShell from '../../Components/Ui/AppShell.vue'
import { useForm } from '@inertiajs/vue3'
const props = defineProps({ group: Object, assessment: { type: Object, default: null }, competencies: { type: Array, default: () => [] } })
const form = useForm({ title: props.assessment?.title ?? '', assessed_on: props.assessment?.assessed_on ?? '', notes: props.assessment?.notes ?? '', tasks: (props.assessment?.tasks ?? [{ title: '', solution: '', max_points: '', level: '', competency_id: '' }]).map(task => ({ id: task.id, title: task.title ?? '', solution: task.solution ?? '', max_points: task.max_points ?? '', level: task.level ?? '', competency_id: task.teaching_unit_competency_id ?? '' })) })
function addTask() { form.tasks.push({ title: '', solution: '', max_points: '', level: '', competency_id: '' }) }
function save() { const url = props.assessment ? `/unterrichtsgruppen/${props.group.id}/lernstandserhebungen/${props.assessment.id}` : `/unterrichtsgruppen/${props.group.id}/lernstandserhebungen`; form[props.assessment ? 'put' : 'post'](url) }
</script>
<template>
    <AppShell><template #toolbar><a :href="`/unterrichtsgruppen/${group.id}/lernstandserhebungen`" class="btn btn-sm btn-light" title="Schließen" aria-label="Schließen"><i class="bi bi-x-lg" aria-hidden="true"></i></a></template><div class="container-full px-3 py-4"><h1 class="h2">{{ assessment ? 'Lernstandserhebung bearbeiten' : 'Neue Lernstandserhebung' }}</h1><form class="card card-body" @submit.prevent="save"><label class="form-label" for="assessment-title">Titel</label><input id="assessment-title" v-model="form.title" class="form-control" required><label class="form-label mt-3" for="assessment-date">Datum</label><input id="assessment-date" v-model="form.assessed_on" type="date" class="form-control"><label class="form-label mt-3" for="assessment-notes">Notizen</label><textarea id="assessment-notes" v-model="form.notes" class="form-control" rows="3"></textarea><h2 class="h5 mt-4">Aufgaben</h2><div v-for="(task, index) in form.tasks" :key="task.id ?? index" class="border rounded p-3 mb-2"><input v-model="task.title" class="form-control mb-2" placeholder="Aufgabe" required><textarea v-model="task.solution" class="form-control mb-2" rows="2" placeholder="Lösung / Erwartungshorizont"></textarea><div class="row g-2"><div class="col"><input v-model="task.max_points" type="number" min="1" class="form-control" placeholder="Max. Punkte"></div><div class="col"><select v-model="task.level" class="form-select"><option value="">Niveau</option><option>G</option><option>M</option><option>E</option></select></div><div class="col-md-6"><select v-model="task.competency_id" class="form-select"><option value="">Kompetenz</option><option v-for="competency in competencies" :key="competency.id" :value="competency.id">{{ competency.local_wording || competency.text || `Kompetenz ${competency.id}` }}</option></select></div></div></div><button class="btn btn-sm btn-outline-secondary" type="button" @click="addTask">Aufgabe hinzufügen</button><div class="d-flex justify-content-end mt-4"><button class="btn btn-primary" type="submit" :disabled="form.processing">Speichern</button></div></form></div></AppShell>
</template>
