<script setup>
import AppShell from '../../Components/Ui/AppShell.vue'
import { useForm } from '@inertiajs/vue3'
import { ref } from 'vue'

const props = defineProps({ group: Object, assessments: Array, students: Array, competencies: Array })
const form = useForm({ title: '', assessed_on: '', notes: '', tasks: [{ title: '', solution: '', max_points: '', level: '', competency_id: '' }] })
const showForm = ref(false)
function addTask() { form.tasks.push({ title: '', solution: '', max_points: '', level: '', competency_id: '' }) }
function store() { form.post(`/unterrichtsgruppen/${props.group.id}/lernstandserhebungen`, { onSuccess: () => { showForm.value = false; form.reset() } }) }
</script>

<template>
    <AppShell>
        <template #toolbar><a :href="`/unterrichtsgruppen/${group.id}`" class="btn btn-sm btn-light" title="Schließen" aria-label="Schließen"><i class="bi bi-x-lg" aria-hidden="true"></i></a><button class="btn btn-sm btn-primary ms-2" type="button" @click="showForm = true"><i class="bi bi-plus-lg me-1" aria-hidden="true"></i>Neue Lernstandserhebung</button></template>
        <div class="container-full px-3 py-4"><h1 class="h2">Lernstandserhebungen · {{ group.name }}</h1><div v-if="$page.props.flash?.success" class="alert alert-success">{{ $page.props.flash.success }}</div><div v-if="!assessments.length" class="card"><div class="card-body text-muted">Noch keine Lernstandserhebung angelegt.</div></div><div v-for="assessment in assessments" :key="assessment.id" class="card mb-3"><div class="card-body"><h2 class="h5">{{ assessment.title }}</h2><p v-if="assessment.assessed_on" class="text-muted">{{ assessment.assessed_on }}</p><ol class="mb-0"><li v-for="task in assessment.tasks" :key="task.id">{{ task.title }}<span v-if="task.level" class="badge text-bg-light ms-2">{{ task.level }}</span><span v-if="task.max_points" class="text-muted ms-2">{{ task.max_points }} Punkte</span></li></ol></div></div></div>
        <div v-if="showForm" class="roo-modal-backdrop" role="presentation" @click.self="showForm = false"><section class="roo-modal" role="dialog" aria-modal="true" aria-label="Neue Lernstandserhebung"><div class="card border-0"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">Neue Lernstandserhebung</h2><button class="btn-close" type="button" aria-label="Schließen" @click="showForm = false"></button></div><form @submit.prevent="store"><label class="form-label" for="assessment-title">Titel</label><input id="assessment-title" v-model="form.title" class="form-control" required><label class="form-label mt-3" for="assessment-date">Datum</label><input id="assessment-date" v-model="form.assessed_on" type="date" class="form-control"><h3 class="h6 mt-4">Aufgaben</h3><div v-for="(task, index) in form.tasks" :key="index" class="border rounded p-3 mb-2"><input v-model="task.title" class="form-control mb-2" placeholder="Aufgabe" required><div class="row g-2"><div class="col"><input v-model="task.max_points" type="number" min="1" class="form-control" placeholder="Max. Punkte"></div><div class="col"><select v-model="task.level" class="form-select"><option value="">Niveau</option><option>G</option><option>M</option><option>E</option></select></div><div class="col"><select v-model="task.competency_id" class="form-select"><option value="">Kompetenz</option><option v-for="competency in competencies" :key="competency.id" :value="competency.id">{{ competency.local_wording || competency.text || `Kompetenz ${competency.id}` }}</option></select></div></div></div><button class="btn btn-sm btn-outline-secondary" type="button" @click="addTask">Aufgabe hinzufügen</button><div class="d-flex justify-content-end gap-2 mt-4"><button class="btn btn-outline-secondary" type="button" @click="showForm = false">Abbrechen</button><button class="btn btn-primary" type="submit" :disabled="form.processing">Speichern</button></div></form></div></div></section></div>
    </AppShell>
</template>
