<script setup>
import AppShell from '../../Components/Ui/AppShell.vue'
import de from '../../i18n/de'
import { useForm, router } from '@inertiajs/vue3'
import { ref } from 'vue'
const props = defineProps({ group: Object, plan: Object, unitTemplates: Array })
const open = ref(false)
const form = useForm({ title: '', starts_on: props.group.school_year.starts_on, ends_on: props.group.school_year.starts_on, planned_hours: 1, unit_template_id: '', is_interrupted: false, notes: '' })
function save() { form.post(`/jahresplanung/${props.group.id}/einheiten`, { onSuccess: () => { open.value = false; form.reset() } }) }
function generate() { router.post(`/jahresplanung/${props.group.id}/stunden-erzeugen`) }
function remove(unit) { if (window.confirm('Diese Unterrichtseinheit aus der Planung entfernen?')) useForm({}).delete(`/jahresplanung/${props.group.id}/einheiten/${unit.id}`) }
function updateStatus(occurrence, status) { useForm({ status, actual_on: occurrence.actual_on, notes: occurrence.notes }).put(`/jahresplanung/${props.group.id}/vorkommnisse/${occurrence.id}`) }
</script>
<template>
    <AppShell><template #toolbar><a href="/jahresplanung" class="btn btn-sm btn-light" :title="de.close" :aria-label="de.close"><i class="bi bi-x-lg" aria-hidden="true"></i></a><button class="btn btn-sm btn-outline-primary" type="button" @click="generate">{{ de.generateLessons }}</button></template>
        <div class="container-full px-3 py-4"><h1 class="h2">{{ de.yearPlans }}: {{ group.name }}</h1><p class="text-muted">{{ group.school.name }} · {{ group.school_year.name }} · {{ group.school_year.starts_on }} – {{ group.school_year.ends_on }}</p><div v-if="$page.props.flash?.success" class="alert alert-success">{{ $page.props.flash.success }}</div>
            <section class="card card-body mb-4"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">{{ de.plannedUnits }}</h2><button class="btn btn-sm btn-outline-primary" type="button" @click="open = true">{{ de.addPlannedUnit }}</button></div><div v-if="!plan.units.length" class="text-muted">{{ de.noPlannedUnits }}</div><div v-for="unit in plan.units" :key="unit.id" class="border rounded p-3 mb-2"><div class="d-flex justify-content-between"><div><strong>{{ unit.title }}</strong><div class="small text-muted">{{ unit.starts_on }} – {{ unit.ends_on }} · {{ unit.planned_hours }} {{ de.hours.toLowerCase() }}<span v-if="unit.template"> · {{ unit.template.title }}</span></div></div><button class="btn btn-sm btn-outline-danger" type="button" @click="remove(unit)"><i class="bi bi-trash" aria-hidden="true"></i></button></div><div v-if="unit.lessons?.[0]?.occurrences?.length" class="mt-3"><div class="small fw-semibold mb-1">{{ de.lessonOccurrences }}</div><div v-for="occurrence in unit.lessons[0].occurrences" :key="occurrence.id" class="d-flex align-items-center gap-2 mb-1"><span class="small">{{ occurrence.planned_on }}</span><select class="form-select form-select-sm w-auto" :value="occurrence.status" @change="updateStatus(occurrence, $event.target.value)"><option v-for="(label, value) in de.statusLabels" :key="value" :value="value">{{ label }}</option></select></div></div></div></section>
            <section v-if="plan.revisions?.length" class="card card-body"><h2 class="h5">{{ de.planHistory }}</h2><div v-for="revision in plan.revisions" :key="revision.id" class="small border-bottom py-2">{{ revision.created_at }} · {{ revision.description }}</div></section>
        </div>
        <div v-if="open" class="roo-modal-backdrop" role="presentation" @click.self="open = false"><section class="roo-modal" role="dialog" aria-modal="true" :aria-label="de.addPlannedUnit"><div class="card border-0"><div class="card-body"><div class="d-flex justify-content-between align-items-center mb-3"><h2 class="h5 mb-0">{{ de.addPlannedUnit }}</h2><button class="btn-close" type="button" :aria-label="de.close" @click="open = false"></button></div><form @submit.prevent="save"><label class="form-label">{{ de.unitTitle }}</label><input v-model="form.title" class="form-control" required><label class="form-label mt-2">{{ de.planTemplate }}</label><select v-model="form.unit_template_id" class="form-select"><option value="">–</option><option v-for="template in unitTemplates" :key="template.id" :value="template.id">{{ template.title }}</option></select><div class="row g-2 mt-1"><div class="col-6"><label class="form-label">{{ de.planStart }}</label><input v-model="form.starts_on" type="date" class="form-control" required></div><div class="col-6"><label class="form-label">{{ de.planEnd }}</label><input v-model="form.ends_on" type="date" class="form-control" required></div></div><label class="form-label mt-2">{{ de.plannedHours }}</label><input v-model="form.planned_hours" type="number" min="1" class="form-control" required><div class="d-flex justify-content-end gap-2 mt-4"><button class="btn btn-outline-secondary" type="button" @click="open = false">{{ de.cancel }}</button><button class="btn btn-primary" type="submit">{{ de.save }}</button></div></form></div></div></section></div>
    </AppShell>
</template>
