<?php

use App\Http\Controllers\CurriculumController;
use App\Http\Controllers\DashboardController;
use App\Http\Controllers\EducationPlanController;
use App\Http\Controllers\SchoolController;
use App\Http\Controllers\SchoolYearController;
use App\Http\Controllers\SearchController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeachingGroupController;
use App\Http\Controllers\TeachingUnitController;
use App\Http\Controllers\LessonWorkspaceController;
use App\Http\Controllers\TeachingUnitResourceController;
use App\Http\Controllers\ResourceLibraryController;
use App\Http\Controllers\SongController;
use App\Http\Controllers\SongbookController;
use App\Http\Controllers\YearPlanController;
use App\Http\Controllers\ProfileController;
use App\Http\Controllers\FluxController;
use Illuminate\Support\Facades\Route;
use Illuminate\Http\Request;
use Inertia\Inertia;

Route::get('/', function (Request $request) {
    if ($request->user()) {
        return to_route('dashboard');
    }

    return Inertia::render('Welcome');
})->name('home');

Route::middleware('auth')->group(function () {
    Route::get('/dashboard', DashboardController::class)->name('dashboard');
    Route::get('/profil', [ProfileController::class, 'show'])->name('profile.show');
    Route::put('/profil', [ProfileController::class, 'update'])->name('profile.update');
    Route::get('/flux/credits', [FluxController::class, 'credits'])->name('flux.credits');
    Route::post('/flux/generate', [FluxController::class, 'generate'])->name('flux.generate');
    Route::get('/flux/poll', [FluxController::class, 'poll'])->name('flux.poll');
    Route::get('/unterricht/{scheduleSlot}', [LessonWorkspaceController::class, 'show'])->name('lessons.show');
    Route::get('/unterricht/{scheduleSlot}/lieder/export', [LessonWorkspaceController::class, 'exportSongs'])->name('lessons.songs.export');
    Route::put('/unterricht/{scheduleSlot}/durchfuehrung', [LessonWorkspaceController::class, 'updateExecution'])->name('lessons.execution.update');
    Route::put('/unterricht/{scheduleSlot}/beobachtungen', [LessonWorkspaceController::class, 'updateObservations'])->name('lessons.observations.update');
    Route::get('/suche', SearchController::class)->name('search');
    Route::get('/bibliothek', ResourceLibraryController::class)->name('resources.library');
    Route::get('/ressourcen/bibliothek', ResourceLibraryController::class);
    Route::get('/bibliothek/lied/neu', [SongController::class, 'create'])->name('songs.create');
    Route::get('/bibliothek/lied/{songVersion}', [SongController::class, 'edit'])->name('songs.versions.edit');
    Route::post('/lieder', [SongController::class, 'store'])->name('songs.store');
    Route::delete('/lieder/{song}', [SongController::class, 'destroy'])->name('songs.destroy');
    Route::post('/lieder/fassungen/{songVersion}/liedblatt', [SongController::class, 'uploadSheet'])->name('songs.sheets.upload');
    Route::get('/lieder/fassungen/{songVersion}/liedblatt', [SongController::class, 'downloadSheet'])->name('songs.sheets.download');
    Route::put('/lieder/fassungen/{songVersion}', [SongController::class, 'updateVersion'])->name('songs.versions.update');
    Route::post('/lieder/fassungen/{songVersion}/bilder', [SongController::class, 'uploadImages'])->name('songs.images.upload');
    Route::post('/lieder/fassungen/{songVersion}/bilder/bibliothek', [SongController::class, 'importLibraryImage'])->name('songs.images.import');
    Route::get('/lieder/fassungen/{songVersion}/bilder/{songImage}', [SongController::class, 'image'])->name('songs.images.show');
    Route::delete('/lieder/fassungen/{songVersion}/bilder/{songImage}', [SongController::class, 'destroyImage'])->name('songs.images.destroy');
    Route::post('/lieder/fassungen/{songVersion}/liedblatt/erzeugen', [SongController::class, 'generateSheet'])->name('songs.sheets.generate');
    Route::get('/lieder/fassungen/{songVersion}/liedblatt/erzeugt/a4', [SongController::class, 'generatedSheet'])->defaults('format', 'a4')->name('songs.sheets.generated-a4');
    Route::get('/lieder/fassungen/{songVersion}/liedblatt/erzeugt/akkord/{instrument}', [SongController::class, 'generatedChordSheet'])->name('songs.sheets.generated-chord');
    Route::get('/lieder/fassungen/{songVersion}/liedblatt/erzeugt', [SongController::class, 'generatedSheet'])->name('songs.sheets.generated');
    Route::post('/ressourcen/bibliothek/dateien', [ResourceLibraryController::class, 'storeFile'])->name('resources.library.files.store');
    Route::post('/ressourcen/bibliothek/ressourcen', [ResourceLibraryController::class, 'storeResource'])->name('resources.library.resources.store');
    Route::post('/ressourcen/bibliothek/materialien', [ResourceLibraryController::class, 'storeMaterial'])->name('resources.library.materials.store');
    Route::post('/ressourcen/bibliothek/materialien/{resource}/bild', [ResourceLibraryController::class, 'uploadMaterialImage'])->name('resources.library.materials.image.upload');
    Route::get('/ressourcen/bibliothek/materialien/{resource}/bild', [ResourceLibraryController::class, 'materialImage'])->name('resources.library.materials.image');
    Route::put('/ressourcen/bibliothek/{kind}/{resource}', [ResourceLibraryController::class, 'updateItem'])->name('resources.library.update');
    Route::delete('/ressourcen/bibliothek/{kind}/{resource}', [ResourceLibraryController::class, 'destroyItem'])->name('resources.library.destroy');
    Route::get('/ressourcen/bibliothek/dateien/{resource}/download', [ResourceLibraryController::class, 'download'])->name('resources.library.files.download');
    Route::get('/ressourcen/bibliothek/dateien/{resource}/preview', [ResourceLibraryController::class, 'preview'])->name('resources.library.files.preview');
    Route::post('/jahresplanung/{teachingGroup}/ressourcen/{resource}/zuordnen', [ResourceLibraryController::class, 'assign'])->name('resources.assign');
    Route::get('/jahresplanung/{teachingGroup}/ressourcen', ResourceLibraryController::class)->name('resources.group-library');
    Route::post('/jahresplanung/{teachingGroup}/ressourcen/{kind}/{resource}/zuordnen', [ResourceLibraryController::class, 'assignItem'])->name('resources.assign-item');
    Route::post('/jahresplanung/{teachingGroup}/ressourcen/{kind}/erstellen', [ResourceLibraryController::class, 'storeAndAssign'])->name('resources.store-and-assign');
    Route::get('/jahresplanung/{teachingGroup}/ressourcen/{kind}/{resource}/zuordnungsstatus', [ResourceLibraryController::class, 'associationStatus'])->name('resources.association-status');
    Route::post('/jahresplanung/{teachingGroup}/ressourcen/{kind}/{resource}/trennen', [ResourceLibraryController::class, 'detach'])->name('resources.detach');
    Route::get('/schulen', [SchoolController::class, 'index'])->name('schools.index');
    Route::get('/schulen/{school}', [SchoolController::class, 'show'])->name('schools.show');
    Route::get('/bildungsplaene', [EducationPlanController::class, 'index'])->name('education-plans.index');
    Route::get('/bildungsplaene/{educationPlan}', [EducationPlanController::class, 'show'])->name('education-plans.show');
    Route::get('/curricula', [CurriculumController::class, 'index'])->name('curricula.index');
    Route::get('/unterrichtseinheiten', [TeachingUnitController::class, 'index'])->name('teaching-units.index');
    Route::post('/unterrichtseinheiten/phasen-vorlagen', [TeachingUnitController::class, 'storePhaseTemplate'])->name('teaching-units.phase-templates.store');
    Route::put('/unterrichtseinheiten/phasen-vorlagen/{phaseTemplate}', [TeachingUnitController::class, 'updatePhaseTemplate'])->name('teaching-units.phase-templates.update');
    Route::delete('/unterrichtseinheiten/phasen-vorlagen/{phaseTemplate}', [TeachingUnitController::class, 'destroyPhaseTemplate'])->name('teaching-units.phase-templates.destroy');
    Route::put('/unterrichtseinheiten/{teachingUnit}', [TeachingUnitController::class, 'update'])->name('teaching-units.update');
    Route::delete('/unterrichtseinheiten/{teachingUnit}', [TeachingUnitController::class, 'destroy'])->name('teaching-units.destroy');
    Route::get('/curricula/vergleichen', [CurriculumController::class, 'compare'])->name('curricula.compare');
    Route::get('/curricula/neu', [CurriculumController::class, 'create'])->name('curricula.create');
    Route::post('/curricula', [CurriculumController::class, 'store'])->name('curricula.store');
    Route::post('/curricula/{curriculum}/fassungen', [CurriculumController::class, 'storeVersion'])->name('curricula.versions.store');
    Route::get('/curricula/{curriculum}', [CurriculumController::class, 'show'])->name('curricula.show');
    Route::get('/unterrichtsgruppen', [TeachingGroupController::class, 'index'])->name('teaching-groups.index');
    Route::get('/jahresplanung', [YearPlanController::class, 'index'])->name('year-plans.index');
    Route::get('/jahresplanung/{teachingGroup}', [YearPlanController::class, 'show'])->name('year-plans.show');
    Route::put('/jahresplanung/{teachingGroup}/präferenzen/curriculum-spalte', [YearPlanController::class, 'updateCurriculumColumnPreference'])->name('year-plans.preferences.curriculum-column');
    Route::post('/jahresplanung/{teachingGroup}/eigene-einheiten', [YearPlanController::class, 'storeTeachingUnit'])->name('year-plans.teaching-units.store');
    Route::post('/jahresplanung/{teachingGroup}/curriculum-themen/alle-uebernehmen', [YearPlanController::class, 'takeAllCurriculumUnits'])->name('year-plans.curriculum-topics.take-all');
    Route::delete('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}', [YearPlanController::class, 'destroyTeachingUnit'])->name('year-plans.teaching-units.destroy');
    Route::put('/jahresplanung/{teachingGroup}/eigene-einheiten/reihenfolge', [YearPlanController::class, 'reorderUnits'])->name('year-plans.teaching-units.reorder');
    Route::put('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}', [YearPlanController::class, 'updateTeachingUnit'])->name('year-plans.teaching-units.update');
    Route::put('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/kompetenzen', [YearPlanController::class, 'updateTeachingUnitCompetencies'])->name('year-plans.teaching-units.competencies');
    Route::post('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/kompetenzen', [YearPlanController::class, 'addTeachingUnitCompetency'])->name('year-plans.teaching-units.competencies.store');
    Route::delete('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/kompetenzen/{teachingUnitCompetency}', [YearPlanController::class, 'removeTeachingUnitCompetency'])->name('year-plans.teaching-units.competencies.destroy');
    Route::post('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/anhaenge', [TeachingUnitResourceController::class, 'store'])->name('year-plans.teaching-units.resources.store');
    Route::put('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/anhaenge/{resource}', [TeachingUnitResourceController::class, 'update'])->name('year-plans.teaching-units.resources.update');
    Route::get('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/anhaenge/{resource}/download', [TeachingUnitResourceController::class, 'download'])->name('year-plans.teaching-units.resources.download');
    Route::get('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/anhaenge/{resource}/preview', [TeachingUnitResourceController::class, 'preview'])->name('year-plans.teaching-units.resources.preview');
    Route::delete('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/anhaenge/{resource}', [TeachingUnitResourceController::class, 'destroy'])->name('year-plans.teaching-units.resources.destroy');
    Route::post('/jahresplanung/{teachingGroup}/eigene-einheiten/importieren', [YearPlanController::class, 'importTeachingUnit'])->name('year-plans.teaching-units.import');
    Route::post('/jahresplanung/{teachingGroup}/curriculum-themen/{topic}/uebernehmen', [YearPlanController::class, 'takeCurriculumUnit'])->name('year-plans.curriculum-topics.take');
    Route::post('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/stunden', [YearPlanController::class, 'storeLesson'])->name('year-plans.lessons.store');
    Route::put('/jahresplanung/{teachingGroup}/lessons/{lesson}', [YearPlanController::class, 'updateLesson'])->name('year-plans.lessons.update');
    Route::delete('/jahresplanung/{teachingGroup}/lessons/{lesson}', [YearPlanController::class, 'destroyLesson'])->name('year-plans.lessons.destroy');
    Route::put('/jahresplanung/{teachingGroup}/lessons/{lesson}/kompetenzen', [YearPlanController::class, 'updateLessonCompetencies'])->name('year-plans.lessons.competencies');
    Route::post('/jahresplanung/{teachingGroup}/lessons/{lesson}/kompetenzen', [YearPlanController::class, 'addLessonCompetency'])->name('year-plans.lessons.competencies.store');
    Route::put('/jahresplanung/{teachingGroup}/phasen/{phase}', [YearPlanController::class, 'updatePhase'])->name('year-plans.phases.update');
    Route::post('/jahresplanung/{teachingGroup}/phasen/{phase}/als-vorlage', [YearPlanController::class, 'savePhaseAsTemplate'])->name('year-plans.phases.save-template');
    Route::post('/jahresplanung/{teachingGroup}/lessons/{lesson}/phasen', [YearPlanController::class, 'storePhase'])->name('year-plans.phases.store');
    Route::delete('/jahresplanung/{teachingGroup}/phasen/{phase}', [YearPlanController::class, 'destroyPhase'])->name('year-plans.phases.destroy');
    Route::put('/jahresplanung/{teachingGroup}/lessons/{lesson}/phasen/reihenfolge', [YearPlanController::class, 'reorderPhases'])->name('year-plans.phases.reorder');
    Route::put('/jahresplanung/{teachingGroup}/geplante-stunden/{scheduledLesson}/status', [YearPlanController::class, 'updateScheduledLessonStatus'])->name('year-plans.scheduled-lessons.status');
    Route::put('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/stunden/reihenfolge', [YearPlanController::class, 'reorderLessons'])->name('year-plans.lessons.reorder');
    Route::post('/jahresplanung/{teachingGroup}/automatisch-einplanen', [YearPlanController::class, 'autoPlan'])->name('year-plans.auto-plan');
    Route::post('/jahresplanung/{teachingGroup}/reflow/rueckgaengig', [YearPlanController::class, 'undoLastReflow'])->name('year-plans.reflow.undo');
    Route::post('/jahresplanung/{teachingGroup}/lessons/{lesson}/einplanen', [YearPlanController::class, 'scheduleLesson'])->name('year-plans.lessons.schedule');
    Route::post('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/einplanen', [YearPlanController::class, 'scheduleUnit'])->name('year-plans.teaching-units.schedule');
    Route::post('/jahresplanung/{teachingGroup}/slots/{scheduleSlot}/einfügen', [YearPlanController::class, 'insertAtSlot'])->name('year-plans.slots.insert');
    Route::delete('/jahresplanung/{teachingGroup}/eigene-einheiten/{teachingUnit}/einplanung', [YearPlanController::class, 'unscheduleUnit'])->name('year-plans.teaching-units.unschedule');
    Route::delete('/jahresplanung/{teachingGroup}/lessons/{lesson}/einplanung', [YearPlanController::class, 'unscheduleLesson'])->name('year-plans.lessons.unschedule');
    Route::put('/jahresplanung/{teachingGroup}/slots/{slot}', [YearPlanController::class, 'updateSlot'])->name('year-plans.slots.update');
    Route::post('/jahresplanung/{teachingGroup}/einheiten', [YearPlanController::class, 'storeUnit'])->name('year-plans.units.store');
    Route::put('/jahresplanung/{teachingGroup}/einheiten/{plannedUnit}', [YearPlanController::class, 'updateUnit'])->name('year-plans.units.update');
    Route::post('/jahresplanung/{teachingGroup}/einheiten/{plannedUnit}/teilen', [YearPlanController::class, 'splitUnit'])->name('year-plans.units.split');
    Route::put('/jahresplanung/{teachingGroup}/einheiten/{plannedUnit}/unterbrechen', [YearPlanController::class, 'interruptUnit'])->name('year-plans.units.interrupt');
    Route::delete('/jahresplanung/{teachingGroup}/einheiten/{plannedUnit}', [YearPlanController::class, 'destroyUnit'])->name('year-plans.units.destroy');
    Route::post('/jahresplanung/{teachingGroup}/stunden-erzeugen', [YearPlanController::class, 'generateLessons'])->name('year-plans.lessons.generate');
    Route::put('/jahresplanung/{teachingGroup}/vorkommnisse/{occurrence}', [YearPlanController::class, 'updateOccurrence'])->name('year-plans.occurrences.update');
    Route::get('/schueler:innen', [StudentController::class, 'index'])->name('students.index');
    Route::get('/schueler:innen/export', [StudentController::class, 'export'])->name('students.export');
    Route::get('/schüler:innen', fn () => to_route('students.index'));
    Route::get('/schuelerinnen', fn () => to_route('students.index'))->name('students.index.legacy');
    Route::post('/unterrichtsgruppen', [TeachingGroupController::class, 'store'])->name('teaching-groups.store');
    Route::get('/unterrichtsgruppen/{teachingGroup}', [TeachingGroupController::class, 'show'])->name('teaching-groups.show');
    Route::post('/unterrichtsgruppen/{teachingGroup}/liederbuch/titelseite', [TeachingGroupController::class, 'uploadSongbookTitlePage'])->name('teaching-groups.songbook.title-page.upload');
    Route::get('/unterrichtsgruppen/{teachingGroup}/liederbuch/titelseite', [TeachingGroupController::class, 'songbookTitlePage'])->name('teaching-groups.songbook.title-page');
    Route::get('/unterrichtsgruppen/{teachingGroup}/liederbuch/songs', [TeachingGroupController::class, 'searchSongbookSongs'])->name('teaching-groups.songbook.songs.search');
    Route::put('/unterrichtsgruppen/{teachingGroup}/liederbuch/lieder', [SongbookController::class, 'updateSongs'])->name('teaching-groups.songbook.songs.update');
    Route::get('/unterrichtsgruppen/{teachingGroup}/liederbuch/export', [SongbookController::class, 'export'])->name('teaching-groups.songbook.export');
    Route::put('/unterrichtsgruppen/{teachingGroup}', [TeachingGroupController::class, 'update'])->name('teaching-groups.update');
    Route::delete('/unterrichtsgruppen/{teachingGroup}', [TeachingGroupController::class, 'destroy'])->name('teaching-groups.destroy');
    Route::post('/unterrichtsgruppen/{teachingGroup}/mitglieder', [TeachingGroupController::class, 'storeMembership'])->name('teaching-groups.memberships.store');
    Route::post('/unterrichtsgruppen/{teachingGroup}/schuelerinnen', [TeachingGroupController::class, 'storeStudentForGroup'])->name('teaching-groups.students.store');
    Route::delete('/unterrichtsgruppen/{teachingGroup}/mitglieder/{student}', [TeachingGroupController::class, 'destroyMembership'])->name('teaching-groups.memberships.destroy');
    Route::post('/unterrichtsgruppen/{teachingGroup}/stundenplan', [TeachingGroupController::class, 'storeTimetableSlot'])->name('teaching-groups.timetable.store');
    Route::put('/unterrichtsgruppen/{teachingGroup}/curricula', [TeachingGroupController::class, 'updateCurricula'])->name('teaching-groups.curricula.update');
    Route::put('/unterrichtsgruppen/{teachingGroup}/stundenraster', [TeachingGroupController::class, 'updatePeriods'])->name('teaching-groups.periods.update');
    Route::put('/unterrichtsgruppen/{teachingGroup}/rituale', [TeachingGroupController::class, 'updateRituals'])->name('teaching-groups.rituals.update');
    Route::post('/schuelerinnen', [TeachingGroupController::class, 'storeStudent'])->name('students.store');
    Route::post('/schuelerinnen/importieren', [TeachingGroupController::class, 'importStudents'])->name('students.import');
    Route::put('/schuelerinnen/{student}', [TeachingGroupController::class, 'updateStudent'])->name('students.update');
    Route::delete('/schuelerinnen/{student}', [TeachingGroupController::class, 'destroyStudent'])->name('students.destroy');
    Route::put('/curricula/{curriculum}', [CurriculumController::class, 'update'])->name('curricula.update');
    Route::delete('/curricula/{curriculum}', [CurriculumController::class, 'destroy'])->name('curricula.destroy');
    Route::post('/curricula/{curriculum}/themen', [CurriculumController::class, 'storeTopic'])->name('curricula.topics.store');
    Route::put('/curricula/{curriculum}/themen/{topic}', [CurriculumController::class, 'updateTopic'])->name('curricula.topics.update');
    Route::post('/curricula/{curriculum}/themen/{topic}/jahr', [CurriculumController::class, 'updateTopicYear'])->name('curricula.topics.year');
    Route::put('/curricula/{curriculum}/themen/{topic}/kompetenzen', [CurriculumController::class, 'updateTopicCompetencies'])->name('curricula.topics.competencies');
    Route::post('/bildungsplaene/{educationPlan}/kompetenzen/{competency}/status', [EducationPlanController::class, 'updateCompetencyStatus'])->name('education-plans.competencies.status');
    Route::post('/schulen', [SchoolController::class, 'store'])->name('schools.store');
    Route::put('/schulen/{school}', [SchoolController::class, 'update'])->name('schools.update');
    Route::put('/schulen/{school}/stundenraster', [SchoolController::class, 'updatePeriods'])->name('schools.periods.update');
    Route::delete('/schulen/{school}', [SchoolController::class, 'destroy'])->name('schools.destroy');
    Route::scopeBindings()->group(function (): void {
        Route::get('/schulen/{school}/{schoolYear}', [SchoolYearController::class, 'show'])->name('school-years.show');
        Route::put('/schulen/{school}/{schoolYear}', [SchoolYearController::class, 'update'])->name('school-years.update');
        Route::post('/schulen/{school}/{schoolYear}/ferien', [SchoolYearController::class, 'storeHoliday'])->name('school-years.holidays.store');
        Route::post('/schulen/{school}/{schoolYear}/ausnahmen', [SchoolYearController::class, 'storeException'])->name('school-years.exceptions.store');
        Route::put('/schulen/{school}/{schoolYear}/tage/{day}', [SchoolYearController::class, 'updateDay'])->name('school-years.days.update');
        Route::post('/schulen/{school}/{schoolYear}/ferien/importieren', [SchoolYearController::class, 'importHolidays'])->name('school-years.holidays.import');
    });
    Route::post('/schuljahre', [SchoolYearController::class, 'store'])->name('school-years.store');
});
