<script setup>
import AppShell from '../../Components/Ui/AppShell.vue'
import { useForm } from '@inertiajs/vue3'
import { ref } from 'vue'
const props = defineProps({ group: Object, periods: Array, students: Array })
const periodForm = useForm({ label: '', starts_on: '', ends_on: '' })
const showPeriod = ref(false)
function storePeriod() { periodForm.post(`/unterrichtsgruppen/${props.group.id}/bewertungen/zeiträume`, { onSuccess: () => { showPeriod.value = false; periodForm.reset() } }) }
</script>
<template>
<AppShell><template #toolbar><a :href="`/unterrichtsgruppen/${group.id}`" class="btn btn-sm btn-light" title="Schließen" aria-label="Schließen"><i class="bi bi-x-lg" aria-hidden="true"></i></a><button class="btn btn-sm btn-primary ms-2" type="button" @click="showPeriod = true"><i class="bi bi-plus-lg me-1" aria-hidden="true"></i>Bewertungszeitraum anlegen</button></template><div class="container-full px-3 py-4"><h1 class="h2">Bewertungen · {{ group.name }}</h1><div v-if="!periods.length" class="card"><div class="card-body text-muted">Noch kein Bewertungszeitraum angelegt.</div></div><div v-for="period in periods" :key="period.id" class="card mb-3"><div class="card-body"><h2 class="h5">{{ period.label }}</h2><div v-for="evaluation in period.evaluations" :key="evaluation.id" class="border-top py-2"><strong>{{ evaluation.student.last_name }}, {{ evaluation.student.first_name }}</strong><span class="badge ms-2" :class="evaluation.status === 'confirmed' ? 'text-bg-success' : 'text-bg-light'">{{ evaluation.status === 'confirmed' ? 'bestätigt' : 'Entwurf' }}</span><p class="mb-0 mt-1 text-pre-wrap">{{ evaluation.draft_text || 'Noch kein Bewertungsentwurf.' }}</p></div></div></div></div><div v-if="showPeriod" class="roo-modal-backdrop" role="presentation" @click.self="showPeriod = false"><section class="roo-modal" role="dialog" aria-modal="true" aria-label="Bewertungszeitraum"><div class="card border-0"><div class="card-body"><h2 class="h5">Bewertungszeitraum anlegen</h2><form @submit.prevent="storePeriod"><input v-model="periodForm.label" class="form-control mb-2" placeholder="z. B. 1. Halbjahr" required><div class="row g-2"><div class="col"><input v-model="periodForm.starts_on" type="date" class="form-control" required></div><div class="col"><input v-model="periodForm.ends_on" type="date" class="form-control" required></div></div><div class="d-flex justify-content-end gap-2 mt-3"><button class="btn btn-outline-secondary" type="button" @click="showPeriod = false">Abbrechen</button><button class="btn btn-primary" type="submit">Speichern</button></div></form></div></div></section></div></AppShell>
</template>
