<script setup>
import AppShell from '../../Components/Ui/AppShell.vue'
import de from '../../i18n/de'
import { useForm } from '@inertiajs/vue3'
const props = defineProps({ sources: Array })
const form = useForm({ title: '', school_type: '', grades: [], source_version_ids: [] })
function toggle(id) { form.source_version_ids = form.source_version_ids.includes(id) ? form.source_version_ids.filter(value => value !== id) : [...form.source_version_ids, id] }
function submit() { form.post('/curricula') }
</script>
<template><AppShell><div class="container py-4"><a href="/curricula">{{ de.curricula }}</a><h1 class="h2 mt-2">{{ de.createCurriculum }}</h1><p class="text-muted">Wähle eine oder mehrere Vorlagen. Die Unterrichtseinheiten werden in dein bearbeitbares Curriculum kopiert.</p><form @submit.prevent="submit" class="card"><div class="card-body"><div class="row g-3 mb-4"><div class="col-md-8"><label class="form-label">{{ de.curriculumTitle }}</label><input v-model="form.title" class="form-control" required><div v-if="form.errors.title" class="text-danger small">{{ form.errors.title }}</div></div><div class="col-md-2"><label class="form-label">{{ de.schoolType }}</label><input v-model="form.school_type" class="form-control"></div><div class="col-md-2"><label class="form-label">{{ de.grades }}</label><input v-model="form.grades" class="form-control" placeholder="5,6" @change="form.grades = String(form.grades).split(',').map(v => Number(v.trim())).filter(Boolean)"></div></div><h2 class="h5">{{ de.sourceCurricula }}</h2><div class="list-group mb-3"><label v-for="source in sources" :key="source.id" class="list-group-item d-flex gap-3 align-items-center"><input class="form-check-input" type="checkbox" :checked="form.source_version_ids.includes(source.id)" @change="toggle(source.id)"><span><strong>{{ source.curriculum.title }}</strong><br><small class="text-muted">{{ [source.curriculum.school_type, source.curriculum.grades?.join(', ')].filter(Boolean).join(' · ') }} · {{ source.topics_count }} {{ de.units }}</small></span></label></div><div v-if="form.errors.source_version_ids" class="text-danger small mb-3">{{ form.errors.source_version_ids }}</div><button class="btn btn-primary" :disabled="form.processing">{{ de.createCurriculum }}</button></div></form></div></AppShell></template>
